@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {

package "Parser Classes" as ParserClasses{
}
package "Representative Commands" as ConcreteCommands {
Class AddCommand
Class FindCommand
Class FlagCommand
Class DashboardCommand
Class ImportCommand
Class SortCommand
}
Class CommandResult
Class "{abstract}\nCommand" as Command


Class "<<interface>>\nLogic" as Logic
Class LogicManager
}

package Model {
Class HiddenModel #FFFFFF
}

package Storage {
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Logic

LogicManager .right.|> Logic
LogicManager -right->"1" ParserClasses
ParserClasses ..> AddCommand : <<create>>
ParserClasses ..> FindCommand : <<create>>
ParserClasses ..> FlagCommand : <<create>>
ParserClasses ..> DashboardCommand : <<create>>
ParserClasses ..> ImportCommand : <<create>>
ParserClasses ..> SortCommand : <<create>>

AddCommand -up-|> Command
FindCommand -up-|> Command
FlagCommand -up-|> Command
DashboardCommand -up-|> Command
ImportCommand -up-|> Command
SortCommand -up-|> Command
LogicManager .left.> Command : <<call>>

LogicManager --> Model
LogicManager --> Storage
Storage --[hidden] Model
Command .[hidden]up.> Storage
Command .right.> Model
note right of ConcreteCommands
Representative command subclasses shown here include newer features
such as FlagCommand, DashboardCommand, ImportCommand, and SortCommand.
Other command classes (e.g. EditCommand, DeleteCommand, FilterCommand,
ExportCommand, TagCommand, UnflagCommand, RemarkCommand, UndoCommand,
RedoCommand, ListCommand, ClearCommand, and HelpCommand) are omitted
for brevity.
end note

Logic ..> CommandResult
LogicManager .down.> CommandResult
Command .up.> CommandResult : <<create>>
@enduml
